# Variables
@baseUrl = http://localhost:3333

# Health check
# @name healthCheck
GET {{baseUrl}}/health

###
# Get rooms
# @name getRooms
# @description This endpoint retrieves a list of all rooms.
# @response 200 - Returns a list of rooms.
GET {{baseUrl}}/rooms

###

# Create room
# @name createRoom
# @description This endpoint creates a new room with the provided name and description.
# @requestBody
# @response 201 - Returns the created room.
POST {{baseUrl}}/rooms
Accept: application/json
Content-Type: application/json

{
  "name": "Sala de Teste",
  "description": "Esta é uma sala de teste para verificar a criação de salas."
}

###

@roomId = {{getRooms.response.body.$.[0].id}}
###

# Get room questions
# @name getRoomQuestions
# @description This endpoint retrieves all questions for a specific room.
# @pathParam roomId - The unique identifier of the room.
# @response 200 - Returns a list of questions for the specified room.
GET {{baseUrl}}/rooms/{{roomId}}/questions


###
# Create question
# @name createQuestion
# @description This endpoint creates a new question in a specific room.
# @pathParam roomId - The unique identifier of the room.
# @requestBody
# @response 201 - Returns the created question.
POST {{baseUrl}}/rooms/{{roomId}}/questions
Accept: application/json
Content-Type: application/json

{
  "question": "Lorem ipsum dolor sit amet?"
}
